# Generated by Django 2.2.7 on 2019-12-01 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Host Name')),
                ('email', models.CharField(max_length=120, verbose_name='Email')),
                ('Phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Visitor Name')),
                ('email', models.CharField(max_length=120, verbose_name='Email')),
                ('Phone', models.IntegerField()),
                ('check_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_v', models.DateTimeField(blank=True, null=True)),
                ('name_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bform.Hosts')),
            ],
        ),
    ]
