# Generated by Django 2.2.7 on 2019-12-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosts',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='visitors',
            old_name='Phone',
            new_name='phone',
        ),
    ]
