# Generated by Django 2.2.7 on 2019-12-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bform', '0002_auto_20191201_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitors',
            old_name='name_h',
            new_name='name_of_host_id',
        ),
    ]
